// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: sdk/zkgov/v1beta1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryCommitmentMerkleProofRequest
type QueryCommitmentMerkleProofRequest struct {
	ProposalId uint64 `protobuf:"varint,1,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`
	Commitment string `protobuf:"bytes,2,opt,name=commitment,proto3" json:"commitment,omitempty"`
}

func (m *QueryCommitmentMerkleProofRequest) Reset()         { *m = QueryCommitmentMerkleProofRequest{} }
func (m *QueryCommitmentMerkleProofRequest) String() string { return proto.CompactTextString(m) }
func (*QueryCommitmentMerkleProofRequest) ProtoMessage()    {}
func (*QueryCommitmentMerkleProofRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac2a1f040192f382, []int{0}
}
func (m *QueryCommitmentMerkleProofRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryCommitmentMerkleProofRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryCommitmentMerkleProofRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryCommitmentMerkleProofRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCommitmentMerkleProofRequest.Merge(m, src)
}
func (m *QueryCommitmentMerkleProofRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryCommitmentMerkleProofRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCommitmentMerkleProofRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCommitmentMerkleProofRequest proto.InternalMessageInfo

// QueryCommitmentMerkleProofResponse
type QueryCommitmentMerkleProofResponse struct {
	MerkleProof     [][]byte `protobuf:"bytes,1,rep,name=merkle_proof,json=merkleProof,proto3" json:"merkle_proof,omitempty"`
	Root            []byte   `protobuf:"bytes,2,opt,name=root,proto3" json:"root,omitempty"`
	CommitmentIndex uint64   `protobuf:"varint,3,opt,name=commitment_index,json=commitmentIndex,proto3" json:"commitment_index,omitempty"`
}

func (m *QueryCommitmentMerkleProofResponse) Reset()         { *m = QueryCommitmentMerkleProofResponse{} }
func (m *QueryCommitmentMerkleProofResponse) String() string { return proto.CompactTextString(m) }
func (*QueryCommitmentMerkleProofResponse) ProtoMessage()    {}
func (*QueryCommitmentMerkleProofResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac2a1f040192f382, []int{1}
}
func (m *QueryCommitmentMerkleProofResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryCommitmentMerkleProofResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryCommitmentMerkleProofResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryCommitmentMerkleProofResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCommitmentMerkleProofResponse.Merge(m, src)
}
func (m *QueryCommitmentMerkleProofResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryCommitmentMerkleProofResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCommitmentMerkleProofResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCommitmentMerkleProofResponse proto.InternalMessageInfo

func (m *QueryCommitmentMerkleProofResponse) GetMerkleProof() [][]byte {
	if m != nil {
		return m.MerkleProof
	}
	return nil
}

func (m *QueryCommitmentMerkleProofResponse) GetRoot() []byte {
	if m != nil {
		return m.Root
	}
	return nil
}

func (m *QueryCommitmentMerkleProofResponse) GetCommitmentIndex() uint64 {
	if m != nil {
		return m.CommitmentIndex
	}
	return 0
}

// QueryProposalAllInfoRequest
type QueryProposalAllInfoRequest struct {
	ProposalId uint64 `protobuf:"varint,1,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`
}

func (m *QueryProposalAllInfoRequest) Reset()         { *m = QueryProposalAllInfoRequest{} }
func (m *QueryProposalAllInfoRequest) String() string { return proto.CompactTextString(m) }
func (*QueryProposalAllInfoRequest) ProtoMessage()    {}
func (*QueryProposalAllInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac2a1f040192f382, []int{2}
}
func (m *QueryProposalAllInfoRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryProposalAllInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryProposalAllInfoRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryProposalAllInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryProposalAllInfoRequest.Merge(m, src)
}
func (m *QueryProposalAllInfoRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryProposalAllInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryProposalAllInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryProposalAllInfoRequest proto.InternalMessageInfo

func (m *QueryProposalAllInfoRequest) GetProposalId() uint64 {
	if m != nil {
		return m.ProposalId
	}
	return 0
}

// QueryProposalAllInfoResponse
type QueryProposalAllInfoResponse struct {
	Votes []*VoteInfo `protobuf:"bytes,1,rep,name=votes,proto3" json:"votes,omitempty"`
}

func (m *QueryProposalAllInfoResponse) Reset()         { *m = QueryProposalAllInfoResponse{} }
func (m *QueryProposalAllInfoResponse) String() string { return proto.CompactTextString(m) }
func (*QueryProposalAllInfoResponse) ProtoMessage()    {}
func (*QueryProposalAllInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac2a1f040192f382, []int{3}
}
func (m *QueryProposalAllInfoResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryProposalAllInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryProposalAllInfoResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryProposalAllInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryProposalAllInfoResponse.Merge(m, src)
}
func (m *QueryProposalAllInfoResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryProposalAllInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryProposalAllInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryProposalAllInfoResponse proto.InternalMessageInfo

func (m *QueryProposalAllInfoResponse) GetVotes() []*VoteInfo {
	if m != nil {
		return m.Votes
	}
	return nil
}

// UserInfo
type UserInfo struct {
	Commitment  string `protobuf:"bytes,1,opt,name=commitment,proto3" json:"commitment,omitempty"`
	UserAddress string `protobuf:"bytes,2,opt,name=user_address,json=userAddress,proto3" json:"user_address,omitempty"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac2a1f040192f382, []int{4}
}
func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return m.Size()
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetCommitment() string {
	if m != nil {
		return m.Commitment
	}
	return ""
}

func (m *UserInfo) GetUserAddress() string {
	if m != nil {
		return m.UserAddress
	}
	return ""
}

// VoteInfo
type VoteInfo struct {
	Nullifer   string     `protobuf:"bytes,1,opt,name=nullifer,proto3" json:"nullifer,omitempty"`
	VoteOption VoteOption `protobuf:"varint,2,opt,name=vote_option,json=voteOption,proto3,enum=sdk.zkgov.v1beta1.VoteOption" json:"vote_option,omitempty"`
}

func (m *VoteInfo) Reset()         { *m = VoteInfo{} }
func (m *VoteInfo) String() string { return proto.CompactTextString(m) }
func (*VoteInfo) ProtoMessage()    {}
func (*VoteInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac2a1f040192f382, []int{5}
}
func (m *VoteInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *VoteInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_VoteInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *VoteInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VoteInfo.Merge(m, src)
}
func (m *VoteInfo) XXX_Size() int {
	return m.Size()
}
func (m *VoteInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_VoteInfo.DiscardUnknown(m)
}

var xxx_messageInfo_VoteInfo proto.InternalMessageInfo

func (m *VoteInfo) GetNullifer() string {
	if m != nil {
		return m.Nullifer
	}
	return ""
}

func (m *VoteInfo) GetVoteOption() VoteOption {
	if m != nil {
		return m.VoteOption
	}
	return VoteOption_VOTE_OPTION_NO
}

// GetProposalRequest
type GetProposalRequest struct {
}

func (m *GetProposalRequest) Reset()         { *m = GetProposalRequest{} }
func (m *GetProposalRequest) String() string { return proto.CompactTextString(m) }
func (*GetProposalRequest) ProtoMessage()    {}
func (*GetProposalRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac2a1f040192f382, []int{6}
}
func (m *GetProposalRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetProposalRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetProposalRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetProposalRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProposalRequest.Merge(m, src)
}
func (m *GetProposalRequest) XXX_Size() int {
	return m.Size()
}
func (m *GetProposalRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProposalRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetProposalRequest proto.InternalMessageInfo

// GetProposalsResponse
type GetProposalsResponse struct {
	Proposals []*Proposal `protobuf:"bytes,1,rep,name=proposals,proto3" json:"proposals,omitempty"`
}

func (m *GetProposalsResponse) Reset()         { *m = GetProposalsResponse{} }
func (m *GetProposalsResponse) String() string { return proto.CompactTextString(m) }
func (*GetProposalsResponse) ProtoMessage()    {}
func (*GetProposalsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac2a1f040192f382, []int{7}
}
func (m *GetProposalsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetProposalsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetProposalsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetProposalsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProposalsResponse.Merge(m, src)
}
func (m *GetProposalsResponse) XXX_Size() int {
	return m.Size()
}
func (m *GetProposalsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProposalsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetProposalsResponse proto.InternalMessageInfo

func (m *GetProposalsResponse) GetProposals() []*Proposal {
	if m != nil {
		return m.Proposals
	}
	return nil
}

// Proposal
type Proposal struct {
	ProposalId           uint64           `protobuf:"varint,1,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`
	Title                string           `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description          string           `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	RegistrationDeadline *types.Timestamp `protobuf:"bytes,4,opt,name=registration_deadline,json=registrationDeadline,proto3" json:"registration_deadline,omitempty"`
	VotingDeadline       *types.Timestamp `protobuf:"bytes,5,opt,name=voting_deadline,json=votingDeadline,proto3" json:"voting_deadline,omitempty"`
}

func (m *Proposal) Reset()         { *m = Proposal{} }
func (m *Proposal) String() string { return proto.CompactTextString(m) }
func (*Proposal) ProtoMessage()    {}
func (*Proposal) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac2a1f040192f382, []int{8}
}
func (m *Proposal) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Proposal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Proposal.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Proposal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Proposal.Merge(m, src)
}
func (m *Proposal) XXX_Size() int {
	return m.Size()
}
func (m *Proposal) XXX_DiscardUnknown() {
	xxx_messageInfo_Proposal.DiscardUnknown(m)
}

var xxx_messageInfo_Proposal proto.InternalMessageInfo

func (m *Proposal) GetProposalId() uint64 {
	if m != nil {
		return m.ProposalId
	}
	return 0
}

func (m *Proposal) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Proposal) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Proposal) GetRegistrationDeadline() *types.Timestamp {
	if m != nil {
		return m.RegistrationDeadline
	}
	return nil
}

func (m *Proposal) GetVotingDeadline() *types.Timestamp {
	if m != nil {
		return m.VotingDeadline
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryCommitmentMerkleProofRequest)(nil), "sdk.zkgov.v1beta1.QueryCommitmentMerkleProofRequest")
	proto.RegisterType((*QueryCommitmentMerkleProofResponse)(nil), "sdk.zkgov.v1beta1.QueryCommitmentMerkleProofResponse")
	proto.RegisterType((*QueryProposalAllInfoRequest)(nil), "sdk.zkgov.v1beta1.QueryProposalAllInfoRequest")
	proto.RegisterType((*QueryProposalAllInfoResponse)(nil), "sdk.zkgov.v1beta1.QueryProposalAllInfoResponse")
	proto.RegisterType((*UserInfo)(nil), "sdk.zkgov.v1beta1.UserInfo")
	proto.RegisterType((*VoteInfo)(nil), "sdk.zkgov.v1beta1.VoteInfo")
	proto.RegisterType((*GetProposalRequest)(nil), "sdk.zkgov.v1beta1.GetProposalRequest")
	proto.RegisterType((*GetProposalsResponse)(nil), "sdk.zkgov.v1beta1.GetProposalsResponse")
	proto.RegisterType((*Proposal)(nil), "sdk.zkgov.v1beta1.Proposal")
}

func init() { proto.RegisterFile("sdk/zkgov/v1beta1/query.proto", fileDescriptor_ac2a1f040192f382) }

var fileDescriptor_ac2a1f040192f382 = []byte{
	// 729 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xcb, 0x6e, 0xd3, 0x4a,
	0x18, 0x8e, 0x9b, 0xe6, 0x28, 0xfd, 0x13, 0xb5, 0xa7, 0x73, 0x52, 0x9d, 0x34, 0x6d, 0x93, 0xd4,
	0x02, 0x11, 0x90, 0x6a, 0xab, 0x01, 0x16, 0xb0, 0xa8, 0x54, 0x8a, 0x84, 0xb2, 0xa8, 0xda, 0x46,
	0xc0, 0x82, 0x4d, 0xe4, 0xc4, 0x13, 0x77, 0xe4, 0xcb, 0xb8, 0x9e, 0x49, 0xd4, 0x8b, 0xba, 0x61,
	0x81, 0x58, 0x82, 0x78, 0x81, 0x3e, 0x02, 0x8f, 0x01, 0xbb, 0x4a, 0x6c, 0x58, 0xa2, 0x96, 0x05,
	0xaf, 0xc0, 0x0e, 0x79, 0xc6, 0x76, 0xa2, 0xd6, 0xbd, 0xb0, 0x9b, 0xf9, 0xfe, 0xdb, 0x37, 0x9f,
	0xbf, 0xdf, 0xb0, 0xc4, 0x4c, 0x5b, 0x3f, 0xb4, 0x2d, 0x3a, 0xd4, 0x87, 0xab, 0x5d, 0xcc, 0x8d,
	0x55, 0x7d, 0x6f, 0x80, 0x83, 0x03, 0xcd, 0x0f, 0x28, 0xa7, 0x68, 0x96, 0x99, 0xb6, 0x26, 0xc2,
	0x5a, 0x14, 0xae, 0x94, 0x2c, 0x6a, 0x51, 0x11, 0xd5, 0xc3, 0x93, 0x4c, 0xac, 0xcc, 0xf7, 0x28,
	0x73, 0x29, 0xeb, 0xc8, 0x80, 0xbc, 0x44, 0xa1, 0x45, 0x8b, 0x52, 0xcb, 0xc1, 0xba, 0xe1, 0x13,
	0xdd, 0xf0, 0x3c, 0xca, 0x0d, 0x4e, 0xa8, 0x17, 0x47, 0x53, 0x08, 0xc8, 0x79, 0x32, 0x5c, 0x8b,
	0x8a, 0xc5, 0xad, 0x3b, 0xe8, 0xeb, 0x9c, 0xb8, 0x98, 0x71, 0xc3, 0xf5, 0x65, 0x82, 0xea, 0xc1,
	0xf2, 0x4e, 0x48, 0x78, 0x83, 0xba, 0x2e, 0xe1, 0x2e, 0xf6, 0xf8, 0x26, 0x0e, 0x6c, 0x07, 0x6f,
	0x07, 0x94, 0xf6, 0xdb, 0x78, 0x6f, 0x80, 0x19, 0x47, 0x35, 0x28, 0xf8, 0x01, 0xf5, 0x29, 0x33,
	0x9c, 0x0e, 0x31, 0xcb, 0x4a, 0x5d, 0x69, 0x4c, 0xb6, 0x21, 0x86, 0x5a, 0x26, 0xaa, 0x02, 0xf4,
	0x92, 0x06, 0xe5, 0x89, 0xba, 0xd2, 0x98, 0x6a, 0x8f, 0x21, 0x4f, 0xf3, 0xef, 0x4f, 0x6a, 0x99,
	0x5f, 0x27, 0xb5, 0x8c, 0xfa, 0x4e, 0x01, 0xf5, 0xba, 0x81, 0xcc, 0xa7, 0x1e, 0xc3, 0x68, 0x19,
	0x8a, 0xae, 0x80, 0x43, 0x45, 0x68, 0xbf, 0xac, 0xd4, 0xb3, 0x8d, 0x62, 0xbb, 0xe0, 0x8e, 0x52,
	0x11, 0x82, 0xc9, 0x80, 0x52, 0x39, 0xad, 0xd8, 0x16, 0x67, 0x74, 0x1f, 0xfe, 0x1d, 0x4d, 0xed,
	0x10, 0xcf, 0xc4, 0xfb, 0xe5, 0xac, 0x60, 0x3b, 0x33, 0xc2, 0x5b, 0x21, 0xac, 0xae, 0xc1, 0x82,
	0xe0, 0xb1, 0x1d, 0xbd, 0x62, 0xdd, 0x71, 0x5a, 0x5e, 0x9f, 0xde, 0xf6, 0xc9, 0xea, 0x0e, 0x2c,
	0xa6, 0xd7, 0x47, 0x2f, 0x58, 0x85, 0xdc, 0x90, 0x72, 0xcc, 0x04, 0xf5, 0x42, 0x73, 0x41, 0xbb,
	0x64, 0x05, 0xed, 0x35, 0xe5, 0x58, 0xd4, 0xc8, 0x4c, 0x75, 0x13, 0xf2, 0xaf, 0x18, 0x0e, 0x42,
	0xe8, 0x82, 0xa2, 0xca, 0x45, 0x45, 0x43, 0x81, 0x06, 0x0c, 0x07, 0x1d, 0xc3, 0x34, 0x03, 0xcc,
	0x58, 0xa4, 0x79, 0x21, 0xc4, 0xd6, 0x25, 0xa4, 0xf6, 0x21, 0x1f, 0x4f, 0x40, 0x15, 0xc8, 0x7b,
	0x03, 0xc7, 0x21, 0x7d, 0x1c, 0x44, 0xcd, 0x92, 0x3b, 0x5a, 0x83, 0x42, 0x38, 0xbf, 0x43, 0xfd,
	0xd0, 0x58, 0xa2, 0xd3, 0x74, 0x73, 0xe9, 0x0a, 0xbe, 0x5b, 0x22, 0xa9, 0x0d, 0xc3, 0xe4, 0xac,
	0x96, 0x00, 0xbd, 0xc0, 0x3c, 0xd6, 0x21, 0x12, 0x50, 0xdd, 0x81, 0xd2, 0x18, 0xca, 0x12, 0x5d,
	0x9e, 0xc0, 0x54, 0xac, 0xe2, 0x75, 0xda, 0x24, 0xed, 0x46, 0xd9, 0xea, 0x6f, 0x05, 0xf2, 0x31,
	0x7e, 0xb3, 0x27, 0x4b, 0x90, 0xe3, 0x84, 0x3b, 0x38, 0x92, 0x46, 0x5e, 0x50, 0x1d, 0x0a, 0x26,
	0x66, 0xbd, 0x80, 0xc8, 0xc7, 0x66, 0xa5, 0x6c, 0x63, 0x10, 0xda, 0x82, 0xb9, 0x00, 0x5b, 0x84,
	0xf1, 0x40, 0x2c, 0x5a, 0xc7, 0xc4, 0x86, 0xe9, 0x10, 0x0f, 0x97, 0x27, 0xeb, 0x4a, 0xa3, 0xd0,
	0xac, 0x68, 0x72, 0xa5, 0xb4, 0x78, 0xa5, 0xb4, 0x97, 0xf1, 0x4a, 0xb5, 0x4b, 0xe3, 0x85, 0xcf,
	0xa3, 0x3a, 0xb4, 0x01, 0x33, 0x43, 0xca, 0x89, 0x67, 0x8d, 0x5a, 0xe5, 0x6e, 0x6c, 0x35, 0x2d,
	0x4b, 0xe2, 0x26, 0xcd, 0xaf, 0x59, 0xc8, 0x09, 0xbf, 0xa1, 0xcf, 0x0a, 0xcc, 0xa5, 0x2e, 0x0f,
	0x7a, 0x94, 0xa2, 0xe3, 0x8d, 0xcb, 0x5d, 0x79, 0xfc, 0x97, 0x55, 0xf2, 0x3b, 0xaa, 0x0f, 0xde,
	0x7e, 0xfb, 0xf9, 0x69, 0xe2, 0x0e, 0x52, 0xf5, 0x43, 0x7b, 0x25, 0xfc, 0xfd, 0x1c, 0x8d, 0x7d,
	0x8e, 0x63, 0xfd, 0x68, 0xe4, 0xd5, 0x63, 0xf4, 0x51, 0x81, 0x99, 0x0b, 0x7b, 0x82, 0xb4, 0xab,
	0xc6, 0xa6, 0x2f, 0x64, 0x45, 0xbf, 0x75, 0x7e, 0x44, 0x70, 0x49, 0x10, 0xfc, 0x1f, 0xcd, 0xa5,
	0x12, 0x44, 0x07, 0x50, 0x1c, 0xf7, 0x27, 0xba, 0x9b, 0xd2, 0xff, 0xb2, 0xad, 0x2b, 0xf7, 0xae,
	0x4f, 0x4b, 0x7c, 0xae, 0xce, 0x8b, 0xf1, 0xff, 0xa1, 0xd9, 0x78, 0x7c, 0xe2, 0xe3, 0x67, 0xad,
	0x2f, 0x67, 0x55, 0xe5, 0xf4, 0xac, 0xaa, 0xfc, 0x38, 0xab, 0x2a, 0x1f, 0xce, 0xab, 0x99, 0xd3,
	0xf3, 0x6a, 0xe6, 0xfb, 0x79, 0x35, 0xf3, 0x46, 0xb7, 0x08, 0xdf, 0x1d, 0x74, 0xb5, 0x1e, 0x75,
	0xf5, 0x21, 0x61, 0xbb, 0x86, 0xb3, 0x62, 0x1b, 0x9e, 0x67, 0xe8, 0x87, 0x76, 0xdc, 0x66, 0x3f,
	0xfa, 0xdb, 0xf3, 0x03, 0x1f, 0xb3, 0xee, 0x3f, 0xc2, 0x3a, 0x0f, 0xff, 0x04, 0x00, 0x00, 0xff,
	0xff, 0x39, 0x2f, 0x03, 0xdb, 0x88, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// CommitmentMerkleProof
	CommitmentMerkleProof(ctx context.Context, in *QueryCommitmentMerkleProofRequest, opts ...grpc.CallOption) (*QueryCommitmentMerkleProofResponse, error)
	// ProposalAllInfo
	ProposalAllInfo(ctx context.Context, in *QueryProposalAllInfoRequest, opts ...grpc.CallOption) (*QueryProposalAllInfoResponse, error)
	// List Proposals
	GetProposals(ctx context.Context, in *GetProposalRequest, opts ...grpc.CallOption) (*GetProposalsResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) CommitmentMerkleProof(ctx context.Context, in *QueryCommitmentMerkleProofRequest, opts ...grpc.CallOption) (*QueryCommitmentMerkleProofResponse, error) {
	out := new(QueryCommitmentMerkleProofResponse)
	err := c.cc.Invoke(ctx, "/sdk.zkgov.v1beta1.Query/CommitmentMerkleProof", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ProposalAllInfo(ctx context.Context, in *QueryProposalAllInfoRequest, opts ...grpc.CallOption) (*QueryProposalAllInfoResponse, error) {
	out := new(QueryProposalAllInfoResponse)
	err := c.cc.Invoke(ctx, "/sdk.zkgov.v1beta1.Query/ProposalAllInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetProposals(ctx context.Context, in *GetProposalRequest, opts ...grpc.CallOption) (*GetProposalsResponse, error) {
	out := new(GetProposalsResponse)
	err := c.cc.Invoke(ctx, "/sdk.zkgov.v1beta1.Query/GetProposals", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// CommitmentMerkleProof
	CommitmentMerkleProof(context.Context, *QueryCommitmentMerkleProofRequest) (*QueryCommitmentMerkleProofResponse, error)
	// ProposalAllInfo
	ProposalAllInfo(context.Context, *QueryProposalAllInfoRequest) (*QueryProposalAllInfoResponse, error)
	// List Proposals
	GetProposals(context.Context, *GetProposalRequest) (*GetProposalsResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) CommitmentMerkleProof(ctx context.Context, req *QueryCommitmentMerkleProofRequest) (*QueryCommitmentMerkleProofResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CommitmentMerkleProof not implemented")
}
func (*UnimplementedQueryServer) ProposalAllInfo(ctx context.Context, req *QueryProposalAllInfoRequest) (*QueryProposalAllInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProposalAllInfo not implemented")
}
func (*UnimplementedQueryServer) GetProposals(ctx context.Context, req *GetProposalRequest) (*GetProposalsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProposals not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_CommitmentMerkleProof_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryCommitmentMerkleProofRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).CommitmentMerkleProof(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sdk.zkgov.v1beta1.Query/CommitmentMerkleProof",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).CommitmentMerkleProof(ctx, req.(*QueryCommitmentMerkleProofRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ProposalAllInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryProposalAllInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ProposalAllInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sdk.zkgov.v1beta1.Query/ProposalAllInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ProposalAllInfo(ctx, req.(*QueryProposalAllInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetProposals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProposalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetProposals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sdk.zkgov.v1beta1.Query/GetProposals",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetProposals(ctx, req.(*GetProposalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sdk.zkgov.v1beta1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CommitmentMerkleProof",
			Handler:    _Query_CommitmentMerkleProof_Handler,
		},
		{
			MethodName: "ProposalAllInfo",
			Handler:    _Query_ProposalAllInfo_Handler,
		},
		{
			MethodName: "GetProposals",
			Handler:    _Query_GetProposals_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sdk/zkgov/v1beta1/query.proto",
}

func (m *QueryCommitmentMerkleProofRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryCommitmentMerkleProofRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryCommitmentMerkleProofRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Commitment) > 0 {
		i -= len(m.Commitment)
		copy(dAtA[i:], m.Commitment)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Commitment)))
		i--
		dAtA[i] = 0x12
	}
	if m.ProposalId != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.ProposalId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryCommitmentMerkleProofResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryCommitmentMerkleProofResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryCommitmentMerkleProofResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CommitmentIndex != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.CommitmentIndex))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Root) > 0 {
		i -= len(m.Root)
		copy(dAtA[i:], m.Root)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Root)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.MerkleProof) > 0 {
		for iNdEx := len(m.MerkleProof) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.MerkleProof[iNdEx])
			copy(dAtA[i:], m.MerkleProof[iNdEx])
			i = encodeVarintQuery(dAtA, i, uint64(len(m.MerkleProof[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryProposalAllInfoRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryProposalAllInfoRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryProposalAllInfoRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ProposalId != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.ProposalId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryProposalAllInfoResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryProposalAllInfoResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryProposalAllInfoResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Votes) > 0 {
		for iNdEx := len(m.Votes) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Votes[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *UserInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UserInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *UserInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.UserAddress) > 0 {
		i -= len(m.UserAddress)
		copy(dAtA[i:], m.UserAddress)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.UserAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Commitment) > 0 {
		i -= len(m.Commitment)
		copy(dAtA[i:], m.Commitment)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Commitment)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *VoteInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VoteInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *VoteInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.VoteOption != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.VoteOption))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Nullifer) > 0 {
		i -= len(m.Nullifer)
		copy(dAtA[i:], m.Nullifer)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Nullifer)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GetProposalRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetProposalRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetProposalRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *GetProposalsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetProposalsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetProposalsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Proposals) > 0 {
		for iNdEx := len(m.Proposals) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Proposals[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *Proposal) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Proposal) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Proposal) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.VotingDeadline != nil {
		{
			size, err := m.VotingDeadline.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	if m.RegistrationDeadline != nil {
		{
			size, err := m.RegistrationDeadline.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Title) > 0 {
		i -= len(m.Title)
		copy(dAtA[i:], m.Title)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Title)))
		i--
		dAtA[i] = 0x12
	}
	if m.ProposalId != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.ProposalId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryCommitmentMerkleProofRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ProposalId != 0 {
		n += 1 + sovQuery(uint64(m.ProposalId))
	}
	l = len(m.Commitment)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryCommitmentMerkleProofResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.MerkleProof) > 0 {
		for _, b := range m.MerkleProof {
			l = len(b)
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	l = len(m.Root)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.CommitmentIndex != 0 {
		n += 1 + sovQuery(uint64(m.CommitmentIndex))
	}
	return n
}

func (m *QueryProposalAllInfoRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ProposalId != 0 {
		n += 1 + sovQuery(uint64(m.ProposalId))
	}
	return n
}

func (m *QueryProposalAllInfoResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Votes) > 0 {
		for _, e := range m.Votes {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *UserInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Commitment)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.UserAddress)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *VoteInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Nullifer)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.VoteOption != 0 {
		n += 1 + sovQuery(uint64(m.VoteOption))
	}
	return n
}

func (m *GetProposalRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *GetProposalsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Proposals) > 0 {
		for _, e := range m.Proposals {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *Proposal) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ProposalId != 0 {
		n += 1 + sovQuery(uint64(m.ProposalId))
	}
	l = len(m.Title)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.RegistrationDeadline != nil {
		l = m.RegistrationDeadline.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.VotingDeadline != nil {
		l = m.VotingDeadline.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryCommitmentMerkleProofRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryCommitmentMerkleProofRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryCommitmentMerkleProofRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProposalId", wireType)
			}
			m.ProposalId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ProposalId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Commitment", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Commitment = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryCommitmentMerkleProofResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryCommitmentMerkleProofResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryCommitmentMerkleProofResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MerkleProof", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MerkleProof = append(m.MerkleProof, make([]byte, postIndex-iNdEx))
			copy(m.MerkleProof[len(m.MerkleProof)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Root", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Root = append(m.Root[:0], dAtA[iNdEx:postIndex]...)
			if m.Root == nil {
				m.Root = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommitmentIndex", wireType)
			}
			m.CommitmentIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CommitmentIndex |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryProposalAllInfoRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryProposalAllInfoRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryProposalAllInfoRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProposalId", wireType)
			}
			m.ProposalId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ProposalId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryProposalAllInfoResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryProposalAllInfoResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryProposalAllInfoResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Votes", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Votes = append(m.Votes, &VoteInfo{})
			if err := m.Votes[len(m.Votes)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *UserInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UserInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UserInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Commitment", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Commitment = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UserAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *VoteInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VoteInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VoteInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nullifer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Nullifer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VoteOption", wireType)
			}
			m.VoteOption = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VoteOption |= VoteOption(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetProposalRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetProposalRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetProposalRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetProposalsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetProposalsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetProposalsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Proposals", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Proposals = append(m.Proposals, &Proposal{})
			if err := m.Proposals[len(m.Proposals)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Proposal) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Proposal: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Proposal: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProposalId", wireType)
			}
			m.ProposalId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ProposalId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Title", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Title = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegistrationDeadline", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.RegistrationDeadline == nil {
				m.RegistrationDeadline = &types.Timestamp{}
			}
			if err := m.RegistrationDeadline.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VotingDeadline", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.VotingDeadline == nil {
				m.VotingDeadline = &types.Timestamp{}
			}
			if err := m.VotingDeadline.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
