// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: sdk/zkgov/v1beta1/query.proto

package zkgovv1beta1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Query_CommitmentMerkleProof_FullMethodName = "/sdk.zkgov.v1beta1.Query/CommitmentMerkleProof"
	Query_ProposalAllInfo_FullMethodName       = "/sdk.zkgov.v1beta1.Query/ProposalAllInfo"
	Query_GetProposals_FullMethodName          = "/sdk.zkgov.v1beta1.Query/GetProposals"
)

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QueryClient interface {
	// CommitmentMerkleProof
	CommitmentMerkleProof(ctx context.Context, in *QueryCommitmentMerkleProofRequest, opts ...grpc.CallOption) (*QueryCommitmentMerkleProofResponse, error)
	// ProposalAllInfo
	ProposalAllInfo(ctx context.Context, in *QueryProposalAllInfoRequest, opts ...grpc.CallOption) (*QueryProposalAllInfoResponse, error)
	// List Proposals
	GetProposals(ctx context.Context, in *GetProposalRequest, opts ...grpc.CallOption) (*GetProposalsResponse, error)
}

type queryClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryClient(cc grpc.ClientConnInterface) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) CommitmentMerkleProof(ctx context.Context, in *QueryCommitmentMerkleProofRequest, opts ...grpc.CallOption) (*QueryCommitmentMerkleProofResponse, error) {
	out := new(QueryCommitmentMerkleProofResponse)
	err := c.cc.Invoke(ctx, Query_CommitmentMerkleProof_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ProposalAllInfo(ctx context.Context, in *QueryProposalAllInfoRequest, opts ...grpc.CallOption) (*QueryProposalAllInfoResponse, error) {
	out := new(QueryProposalAllInfoResponse)
	err := c.cc.Invoke(ctx, Query_ProposalAllInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetProposals(ctx context.Context, in *GetProposalRequest, opts ...grpc.CallOption) (*GetProposalsResponse, error) {
	out := new(GetProposalsResponse)
	err := c.cc.Invoke(ctx, Query_GetProposals_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
// All implementations must embed UnimplementedQueryServer
// for forward compatibility
type QueryServer interface {
	// CommitmentMerkleProof
	CommitmentMerkleProof(context.Context, *QueryCommitmentMerkleProofRequest) (*QueryCommitmentMerkleProofResponse, error)
	// ProposalAllInfo
	ProposalAllInfo(context.Context, *QueryProposalAllInfoRequest) (*QueryProposalAllInfoResponse, error)
	// List Proposals
	GetProposals(context.Context, *GetProposalRequest) (*GetProposalsResponse, error)
	mustEmbedUnimplementedQueryServer()
}

// UnimplementedQueryServer must be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (UnimplementedQueryServer) CommitmentMerkleProof(context.Context, *QueryCommitmentMerkleProofRequest) (*QueryCommitmentMerkleProofResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CommitmentMerkleProof not implemented")
}
func (UnimplementedQueryServer) ProposalAllInfo(context.Context, *QueryProposalAllInfoRequest) (*QueryProposalAllInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProposalAllInfo not implemented")
}
func (UnimplementedQueryServer) GetProposals(context.Context, *GetProposalRequest) (*GetProposalsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProposals not implemented")
}
func (UnimplementedQueryServer) mustEmbedUnimplementedQueryServer() {}

// UnsafeQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryServer will
// result in compilation errors.
type UnsafeQueryServer interface {
	mustEmbedUnimplementedQueryServer()
}

func RegisterQueryServer(s grpc.ServiceRegistrar, srv QueryServer) {
	s.RegisterService(&Query_ServiceDesc, srv)
}

func _Query_CommitmentMerkleProof_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryCommitmentMerkleProofRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).CommitmentMerkleProof(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_CommitmentMerkleProof_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).CommitmentMerkleProof(ctx, req.(*QueryCommitmentMerkleProofRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ProposalAllInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryProposalAllInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ProposalAllInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_ProposalAllInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ProposalAllInfo(ctx, req.(*QueryProposalAllInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetProposals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProposalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetProposals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_GetProposals_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetProposals(ctx, req.(*GetProposalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Query_ServiceDesc is the grpc.ServiceDesc for Query service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Query_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sdk.zkgov.v1beta1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CommitmentMerkleProof",
			Handler:    _Query_CommitmentMerkleProof_Handler,
		},
		{
			MethodName: "ProposalAllInfo",
			Handler:    _Query_ProposalAllInfo_Handler,
		},
		{
			MethodName: "GetProposals",
			Handler:    _Query_GetProposals_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sdk/zkgov/v1beta1/query.proto",
}
