// Code generated by protoc-gen-go-pulsar. DO NOT EDIT.
package zkgovv1beta1

import (
	fmt "fmt"
	runtime "github.com/cosmos/cosmos-proto/runtime"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	io "io"
	reflect "reflect"
	sync "sync"
)

var (
	md_Commitment               protoreflect.MessageDescriptor
	fd_Commitment_commitment    protoreflect.FieldDescriptor
	fd_Commitment_commitment_id protoreflect.FieldDescriptor
)

func init() {
	file_sdk_zkgov_v1beta1_zkgov_proto_init()
	md_Commitment = File_sdk_zkgov_v1beta1_zkgov_proto.Messages().ByName("Commitment")
	fd_Commitment_commitment = md_Commitment.Fields().ByName("commitment")
	fd_Commitment_commitment_id = md_Commitment.Fields().ByName("commitment_id")
}

var _ protoreflect.Message = (*fastReflection_Commitment)(nil)

type fastReflection_Commitment Commitment

func (x *Commitment) ProtoReflect() protoreflect.Message {
	return (*fastReflection_Commitment)(x)
}

func (x *Commitment) slowProtoReflect() protoreflect.Message {
	mi := &file_sdk_zkgov_v1beta1_zkgov_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_Commitment_messageType fastReflection_Commitment_messageType
var _ protoreflect.MessageType = fastReflection_Commitment_messageType{}

type fastReflection_Commitment_messageType struct{}

func (x fastReflection_Commitment_messageType) Zero() protoreflect.Message {
	return (*fastReflection_Commitment)(nil)
}
func (x fastReflection_Commitment_messageType) New() protoreflect.Message {
	return new(fastReflection_Commitment)
}
func (x fastReflection_Commitment_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_Commitment
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_Commitment) Descriptor() protoreflect.MessageDescriptor {
	return md_Commitment
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_Commitment) Type() protoreflect.MessageType {
	return _fastReflection_Commitment_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_Commitment) New() protoreflect.Message {
	return new(fastReflection_Commitment)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_Commitment) Interface() protoreflect.ProtoMessage {
	return (*Commitment)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_Commitment) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.Commitment != "" {
		value := protoreflect.ValueOfString(x.Commitment)
		if !f(fd_Commitment_commitment, value) {
			return
		}
	}
	if x.CommitmentId != uint64(0) {
		value := protoreflect.ValueOfUint64(x.CommitmentId)
		if !f(fd_Commitment_commitment_id, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_Commitment) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "sdk.zkgov.v1beta1.Commitment.commitment":
		return x.Commitment != ""
	case "sdk.zkgov.v1beta1.Commitment.commitment_id":
		return x.CommitmentId != uint64(0)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: sdk.zkgov.v1beta1.Commitment"))
		}
		panic(fmt.Errorf("message sdk.zkgov.v1beta1.Commitment does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Commitment) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "sdk.zkgov.v1beta1.Commitment.commitment":
		x.Commitment = ""
	case "sdk.zkgov.v1beta1.Commitment.commitment_id":
		x.CommitmentId = uint64(0)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: sdk.zkgov.v1beta1.Commitment"))
		}
		panic(fmt.Errorf("message sdk.zkgov.v1beta1.Commitment does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_Commitment) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "sdk.zkgov.v1beta1.Commitment.commitment":
		value := x.Commitment
		return protoreflect.ValueOfString(value)
	case "sdk.zkgov.v1beta1.Commitment.commitment_id":
		value := x.CommitmentId
		return protoreflect.ValueOfUint64(value)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: sdk.zkgov.v1beta1.Commitment"))
		}
		panic(fmt.Errorf("message sdk.zkgov.v1beta1.Commitment does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Commitment) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "sdk.zkgov.v1beta1.Commitment.commitment":
		x.Commitment = value.Interface().(string)
	case "sdk.zkgov.v1beta1.Commitment.commitment_id":
		x.CommitmentId = value.Uint()
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: sdk.zkgov.v1beta1.Commitment"))
		}
		panic(fmt.Errorf("message sdk.zkgov.v1beta1.Commitment does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Commitment) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "sdk.zkgov.v1beta1.Commitment.commitment":
		panic(fmt.Errorf("field commitment of message sdk.zkgov.v1beta1.Commitment is not mutable"))
	case "sdk.zkgov.v1beta1.Commitment.commitment_id":
		panic(fmt.Errorf("field commitment_id of message sdk.zkgov.v1beta1.Commitment is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: sdk.zkgov.v1beta1.Commitment"))
		}
		panic(fmt.Errorf("message sdk.zkgov.v1beta1.Commitment does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_Commitment) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "sdk.zkgov.v1beta1.Commitment.commitment":
		return protoreflect.ValueOfString("")
	case "sdk.zkgov.v1beta1.Commitment.commitment_id":
		return protoreflect.ValueOfUint64(uint64(0))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: sdk.zkgov.v1beta1.Commitment"))
		}
		panic(fmt.Errorf("message sdk.zkgov.v1beta1.Commitment does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_Commitment) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in sdk.zkgov.v1beta1.Commitment", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_Commitment) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Commitment) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_Commitment) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_Commitment) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*Commitment)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		l = len(x.Commitment)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.CommitmentId != 0 {
			n += 1 + runtime.Sov(uint64(x.CommitmentId))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*Commitment)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if x.CommitmentId != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.CommitmentId))
			i--
			dAtA[i] = 0x10
		}
		if len(x.Commitment) > 0 {
			i -= len(x.Commitment)
			copy(dAtA[i:], x.Commitment)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Commitment)))
			i--
			dAtA[i] = 0xa
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*Commitment)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: Commitment: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: Commitment: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Commitment", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Commitment = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 2:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field CommitmentId", wireType)
				}
				x.CommitmentId = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.CommitmentId |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

var (
	md_User               protoreflect.MessageDescriptor
	fd_User_userid        protoreflect.FieldDescriptor
	fd_User_commitment    protoreflect.FieldDescriptor
	fd_User_random_number protoreflect.FieldDescriptor
	fd_User_nullifier     protoreflect.FieldDescriptor
)

func init() {
	file_sdk_zkgov_v1beta1_zkgov_proto_init()
	md_User = File_sdk_zkgov_v1beta1_zkgov_proto.Messages().ByName("User")
	fd_User_userid = md_User.Fields().ByName("userid")
	fd_User_commitment = md_User.Fields().ByName("commitment")
	fd_User_random_number = md_User.Fields().ByName("random_number")
	fd_User_nullifier = md_User.Fields().ByName("nullifier")
}

var _ protoreflect.Message = (*fastReflection_User)(nil)

type fastReflection_User User

func (x *User) ProtoReflect() protoreflect.Message {
	return (*fastReflection_User)(x)
}

func (x *User) slowProtoReflect() protoreflect.Message {
	mi := &file_sdk_zkgov_v1beta1_zkgov_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_User_messageType fastReflection_User_messageType
var _ protoreflect.MessageType = fastReflection_User_messageType{}

type fastReflection_User_messageType struct{}

func (x fastReflection_User_messageType) Zero() protoreflect.Message {
	return (*fastReflection_User)(nil)
}
func (x fastReflection_User_messageType) New() protoreflect.Message {
	return new(fastReflection_User)
}
func (x fastReflection_User_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_User
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_User) Descriptor() protoreflect.MessageDescriptor {
	return md_User
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_User) Type() protoreflect.MessageType {
	return _fastReflection_User_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_User) New() protoreflect.Message {
	return new(fastReflection_User)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_User) Interface() protoreflect.ProtoMessage {
	return (*User)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_User) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.Userid != uint64(0) {
		value := protoreflect.ValueOfUint64(x.Userid)
		if !f(fd_User_userid, value) {
			return
		}
	}
	if len(x.Commitment) != 0 {
		value := protoreflect.ValueOfBytes(x.Commitment)
		if !f(fd_User_commitment, value) {
			return
		}
	}
	if x.RandomNumber != uint64(0) {
		value := protoreflect.ValueOfUint64(x.RandomNumber)
		if !f(fd_User_random_number, value) {
			return
		}
	}
	if len(x.Nullifier) != 0 {
		value := protoreflect.ValueOfBytes(x.Nullifier)
		if !f(fd_User_nullifier, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_User) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "sdk.zkgov.v1beta1.User.userid":
		return x.Userid != uint64(0)
	case "sdk.zkgov.v1beta1.User.commitment":
		return len(x.Commitment) != 0
	case "sdk.zkgov.v1beta1.User.random_number":
		return x.RandomNumber != uint64(0)
	case "sdk.zkgov.v1beta1.User.nullifier":
		return len(x.Nullifier) != 0
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: sdk.zkgov.v1beta1.User"))
		}
		panic(fmt.Errorf("message sdk.zkgov.v1beta1.User does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_User) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "sdk.zkgov.v1beta1.User.userid":
		x.Userid = uint64(0)
	case "sdk.zkgov.v1beta1.User.commitment":
		x.Commitment = nil
	case "sdk.zkgov.v1beta1.User.random_number":
		x.RandomNumber = uint64(0)
	case "sdk.zkgov.v1beta1.User.nullifier":
		x.Nullifier = nil
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: sdk.zkgov.v1beta1.User"))
		}
		panic(fmt.Errorf("message sdk.zkgov.v1beta1.User does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_User) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "sdk.zkgov.v1beta1.User.userid":
		value := x.Userid
		return protoreflect.ValueOfUint64(value)
	case "sdk.zkgov.v1beta1.User.commitment":
		value := x.Commitment
		return protoreflect.ValueOfBytes(value)
	case "sdk.zkgov.v1beta1.User.random_number":
		value := x.RandomNumber
		return protoreflect.ValueOfUint64(value)
	case "sdk.zkgov.v1beta1.User.nullifier":
		value := x.Nullifier
		return protoreflect.ValueOfBytes(value)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: sdk.zkgov.v1beta1.User"))
		}
		panic(fmt.Errorf("message sdk.zkgov.v1beta1.User does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_User) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "sdk.zkgov.v1beta1.User.userid":
		x.Userid = value.Uint()
	case "sdk.zkgov.v1beta1.User.commitment":
		x.Commitment = value.Bytes()
	case "sdk.zkgov.v1beta1.User.random_number":
		x.RandomNumber = value.Uint()
	case "sdk.zkgov.v1beta1.User.nullifier":
		x.Nullifier = value.Bytes()
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: sdk.zkgov.v1beta1.User"))
		}
		panic(fmt.Errorf("message sdk.zkgov.v1beta1.User does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_User) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "sdk.zkgov.v1beta1.User.userid":
		panic(fmt.Errorf("field userid of message sdk.zkgov.v1beta1.User is not mutable"))
	case "sdk.zkgov.v1beta1.User.commitment":
		panic(fmt.Errorf("field commitment of message sdk.zkgov.v1beta1.User is not mutable"))
	case "sdk.zkgov.v1beta1.User.random_number":
		panic(fmt.Errorf("field random_number of message sdk.zkgov.v1beta1.User is not mutable"))
	case "sdk.zkgov.v1beta1.User.nullifier":
		panic(fmt.Errorf("field nullifier of message sdk.zkgov.v1beta1.User is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: sdk.zkgov.v1beta1.User"))
		}
		panic(fmt.Errorf("message sdk.zkgov.v1beta1.User does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_User) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "sdk.zkgov.v1beta1.User.userid":
		return protoreflect.ValueOfUint64(uint64(0))
	case "sdk.zkgov.v1beta1.User.commitment":
		return protoreflect.ValueOfBytes(nil)
	case "sdk.zkgov.v1beta1.User.random_number":
		return protoreflect.ValueOfUint64(uint64(0))
	case "sdk.zkgov.v1beta1.User.nullifier":
		return protoreflect.ValueOfBytes(nil)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: sdk.zkgov.v1beta1.User"))
		}
		panic(fmt.Errorf("message sdk.zkgov.v1beta1.User does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_User) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in sdk.zkgov.v1beta1.User", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_User) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_User) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_User) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_User) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*User)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		if x.Userid != 0 {
			n += 1 + runtime.Sov(uint64(x.Userid))
		}
		l = len(x.Commitment)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.RandomNumber != 0 {
			n += 1 + runtime.Sov(uint64(x.RandomNumber))
		}
		l = len(x.Nullifier)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*User)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if len(x.Nullifier) > 0 {
			i -= len(x.Nullifier)
			copy(dAtA[i:], x.Nullifier)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Nullifier)))
			i--
			dAtA[i] = 0x22
		}
		if x.RandomNumber != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.RandomNumber))
			i--
			dAtA[i] = 0x18
		}
		if len(x.Commitment) > 0 {
			i -= len(x.Commitment)
			copy(dAtA[i:], x.Commitment)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Commitment)))
			i--
			dAtA[i] = 0x12
		}
		if x.Userid != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.Userid))
			i--
			dAtA[i] = 0x8
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*User)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: User: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: User: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Userid", wireType)
				}
				x.Userid = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.Userid |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 2:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Commitment", wireType)
				}
				var byteLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					byteLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if byteLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + byteLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Commitment = append(x.Commitment[:0], dAtA[iNdEx:postIndex]...)
				if x.Commitment == nil {
					x.Commitment = []byte{}
				}
				iNdEx = postIndex
			case 3:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field RandomNumber", wireType)
				}
				x.RandomNumber = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.RandomNumber |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 4:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Nullifier", wireType)
				}
				var byteLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					byteLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if byteLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + byteLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Nullifier = append(x.Nullifier[:0], dAtA[iNdEx:postIndex]...)
				if x.Nullifier == nil {
					x.Nullifier = []byte{}
				}
				iNdEx = postIndex
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        (unknown)
// source: sdk/zkgov/v1beta1/zkgov.proto

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VoteOption int32

const (
	VoteOption_VOTE_OPTION_NO  VoteOption = 0
	VoteOption_VOTE_OPTION_YES VoteOption = 1
)

// Enum value maps for VoteOption.
var (
	VoteOption_name = map[int32]string{
		0: "VOTE_OPTION_NO",
		1: "VOTE_OPTION_YES",
	}
	VoteOption_value = map[string]int32{
		"VOTE_OPTION_NO":  0,
		"VOTE_OPTION_YES": 1,
	}
)

func (x VoteOption) Enum() *VoteOption {
	p := new(VoteOption)
	*p = x
	return p
}

func (x VoteOption) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VoteOption) Descriptor() protoreflect.EnumDescriptor {
	return file_sdk_zkgov_v1beta1_zkgov_proto_enumTypes[0].Descriptor()
}

func (VoteOption) Type() protoreflect.EnumType {
	return &file_sdk_zkgov_v1beta1_zkgov_proto_enumTypes[0]
}

func (x VoteOption) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VoteOption.Descriptor instead.
func (VoteOption) EnumDescriptor() ([]byte, []int) {
	return file_sdk_zkgov_v1beta1_zkgov_proto_rawDescGZIP(), []int{0}
}

// commitment
type Commitment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Commitment   string `protobuf:"bytes,1,opt,name=commitment,proto3" json:"commitment,omitempty"`
	CommitmentId uint64 `protobuf:"varint,2,opt,name=commitment_id,json=commitmentId,proto3" json:"commitment_id,omitempty"`
}

func (x *Commitment) Reset() {
	*x = Commitment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdk_zkgov_v1beta1_zkgov_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Commitment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Commitment) ProtoMessage() {}

// Deprecated: Use Commitment.ProtoReflect.Descriptor instead.
func (*Commitment) Descriptor() ([]byte, []int) {
	return file_sdk_zkgov_v1beta1_zkgov_proto_rawDescGZIP(), []int{0}
}

func (x *Commitment) GetCommitment() string {
	if x != nil {
		return x.Commitment
	}
	return ""
}

func (x *Commitment) GetCommitmentId() uint64 {
	if x != nil {
		return x.CommitmentId
	}
	return 0
}

// user
type User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Userid       uint64 `protobuf:"varint,1,opt,name=userid,proto3" json:"userid,omitempty"`
	Commitment   []byte `protobuf:"bytes,2,opt,name=commitment,proto3" json:"commitment,omitempty"`
	RandomNumber uint64 `protobuf:"varint,3,opt,name=random_number,json=randomNumber,proto3" json:"random_number,omitempty"`
	Nullifier    []byte `protobuf:"bytes,4,opt,name=nullifier,proto3" json:"nullifier,omitempty"`
}

func (x *User) Reset() {
	*x = User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdk_zkgov_v1beta1_zkgov_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_sdk_zkgov_v1beta1_zkgov_proto_rawDescGZIP(), []int{1}
}

func (x *User) GetUserid() uint64 {
	if x != nil {
		return x.Userid
	}
	return 0
}

func (x *User) GetCommitment() []byte {
	if x != nil {
		return x.Commitment
	}
	return nil
}

func (x *User) GetRandomNumber() uint64 {
	if x != nil {
		return x.RandomNumber
	}
	return 0
}

func (x *User) GetNullifier() []byte {
	if x != nil {
		return x.Nullifier
	}
	return nil
}

var File_sdk_zkgov_v1beta1_zkgov_proto protoreflect.FileDescriptor

var file_sdk_zkgov_v1beta1_zkgov_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x73, 0x64, 0x6b, 0x2f, 0x7a, 0x6b, 0x67, 0x6f, 0x76, 0x2f, 0x76, 0x31, 0x62, 0x65,
	0x74, 0x61, 0x31, 0x2f, 0x7a, 0x6b, 0x67, 0x6f, 0x76, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x11, 0x73, 0x64, 0x6b, 0x2e, 0x7a, 0x6b, 0x67, 0x6f, 0x76, 0x2e, 0x76, 0x31, 0x62, 0x65, 0x74,
	0x61, 0x31, 0x22, 0x51, 0x0a, 0x0a, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74,
	0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74,
	0x12, 0x23, 0x0a, 0x0d, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d,
	0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x81, 0x01, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x12, 0x16,
	0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x69, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74,
	0x6d, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x63, 0x6f, 0x6d, 0x6d,
	0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x61, 0x6e, 0x64, 0x6f, 0x6d,
	0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0c, 0x72,
	0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x6e,
	0x75, 0x6c, 0x6c, 0x69, 0x66, 0x69, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09,
	0x6e, 0x75, 0x6c, 0x6c, 0x69, 0x66, 0x69, 0x65, 0x72, 0x2a, 0x35, 0x0a, 0x0a, 0x56, 0x6f, 0x74,
	0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x0e, 0x56, 0x4f, 0x54, 0x45, 0x5f,
	0x4f, 0x50, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x4e, 0x4f, 0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f, 0x56,
	0x4f, 0x54, 0x45, 0x5f, 0x4f, 0x50, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x59, 0x45, 0x53, 0x10, 0x01,
	0x42, 0xba, 0x01, 0x0a, 0x15, 0x63, 0x6f, 0x6d, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x7a, 0x6b, 0x67,
	0x6f, 0x76, 0x2e, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x42, 0x0a, 0x5a, 0x6b, 0x67, 0x6f,
	0x76, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x2f, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73,
	0x73, 0x64, 0x6b, 0x2e, 0x69, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x64, 0x6b, 0x2f, 0x7a,
	0x6b, 0x67, 0x6f, 0x76, 0x2f, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x3b, 0x7a, 0x6b, 0x67,
	0x6f, 0x76, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0xa2, 0x02, 0x03, 0x53, 0x5a, 0x58, 0xaa,
	0x02, 0x11, 0x53, 0x64, 0x6b, 0x2e, 0x5a, 0x6b, 0x67, 0x6f, 0x76, 0x2e, 0x56, 0x31, 0x62, 0x65,
	0x74, 0x61, 0x31, 0xca, 0x02, 0x11, 0x53, 0x64, 0x6b, 0x5c, 0x5a, 0x6b, 0x67, 0x6f, 0x76, 0x5c,
	0x56, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0xe2, 0x02, 0x1d, 0x53, 0x64, 0x6b, 0x5c, 0x5a, 0x6b,
	0x67, 0x6f, 0x76, 0x5c, 0x56, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x13, 0x53, 0x64, 0x6b, 0x3a, 0x3a, 0x5a,
	0x6b, 0x67, 0x6f, 0x76, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sdk_zkgov_v1beta1_zkgov_proto_rawDescOnce sync.Once
	file_sdk_zkgov_v1beta1_zkgov_proto_rawDescData = file_sdk_zkgov_v1beta1_zkgov_proto_rawDesc
)

func file_sdk_zkgov_v1beta1_zkgov_proto_rawDescGZIP() []byte {
	file_sdk_zkgov_v1beta1_zkgov_proto_rawDescOnce.Do(func() {
		file_sdk_zkgov_v1beta1_zkgov_proto_rawDescData = protoimpl.X.CompressGZIP(file_sdk_zkgov_v1beta1_zkgov_proto_rawDescData)
	})
	return file_sdk_zkgov_v1beta1_zkgov_proto_rawDescData
}

var file_sdk_zkgov_v1beta1_zkgov_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sdk_zkgov_v1beta1_zkgov_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sdk_zkgov_v1beta1_zkgov_proto_goTypes = []interface{}{
	(VoteOption)(0),    // 0: sdk.zkgov.v1beta1.VoteOption
	(*Commitment)(nil), // 1: sdk.zkgov.v1beta1.Commitment
	(*User)(nil),       // 2: sdk.zkgov.v1beta1.User
}
var file_sdk_zkgov_v1beta1_zkgov_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sdk_zkgov_v1beta1_zkgov_proto_init() }
func file_sdk_zkgov_v1beta1_zkgov_proto_init() {
	if File_sdk_zkgov_v1beta1_zkgov_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sdk_zkgov_v1beta1_zkgov_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Commitment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sdk_zkgov_v1beta1_zkgov_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sdk_zkgov_v1beta1_zkgov_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sdk_zkgov_v1beta1_zkgov_proto_goTypes,
		DependencyIndexes: file_sdk_zkgov_v1beta1_zkgov_proto_depIdxs,
		EnumInfos:         file_sdk_zkgov_v1beta1_zkgov_proto_enumTypes,
		MessageInfos:      file_sdk_zkgov_v1beta1_zkgov_proto_msgTypes,
	}.Build()
	File_sdk_zkgov_v1beta1_zkgov_proto = out.File
	file_sdk_zkgov_v1beta1_zkgov_proto_rawDesc = nil
	file_sdk_zkgov_v1beta1_zkgov_proto_goTypes = nil
	file_sdk_zkgov_v1beta1_zkgov_proto_depIdxs = nil
}
